# Generated by Django 2.2.3 on 2019-07-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagecarouselimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecarouselimages',
            old_name='carosuel_image',
            new_name='carosuel_images',
        ),
    ]
