# Generated by Django 2.2.3 on 2019-07-17 20:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='add your text', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Some More Text!!', required=True))]))], blank=True, null=True),
        ),
    ]
